filter2 = df['Type of Incident'].isin(['UNAUTHORIZED USE OF MOTOR VEH                            ',
                                       'BMV                                                      ',
                                       'ABANDONED/FOUND PROPERTY NO OFFENSE                      ',
                                       'UNAUTHORIZED USE OF MOTOR VEH ATT                        ',
                                       'PUBLIC INTOXICATION                                      ',
                                       'CRIM MISCHIEF greater than OR EQUAL $100 less than $750  ',
                                       'RECOVERED OUT OF TOWN STOLEN VEHICLE NO OFFENSE          ',
                                       'CRIMINAL TRESPASS WARNING                                ',
                                       'LOST PROPERTY NO OFFENSE                                 ',
                                       'ROBBERY OF INDIVIDUAL AGG                                ',
                                       'BURGLARY OF BUILDING - FORCED ENTRY                      ',
                                       'BURGLARY OF HABITATION - FORCED ENTRY                    ',
                                       'APOWW SOCIAL SERVICES REFERRAL                           ',
                                       'POSS MARIJUANA less than2OZ                              ',
                                       'RECKLESS DAMAGE                                          ',
                                       'ASSAULT -BODILY INJURY                                   ',
                                       'BURGLARY OF HABITATION -NO FORCED ENTRY                  ',
                                       'THEFT OF PROP greater than OR EQUAL $100 less than $750  ',
                                       'ASSAULT AGG                                              ',
                                       'CRIM MISCHIEF greater than or EQUAL $750 less than $2,500'])
